import { Effect, Layer, Option, Ref } from "effect"

import { PersistenceError } from "../../../shared/errors.js"
import type { SampleImage , FilmId} from "../domain/film.js"
import { Film, makeFilmId } from "../domain/film.js"
import type { GroupBuy } from "../domain/groupBuy.js"
import type { HubId } from "../domain/hub.js"
import { Hub, makeHubId } from "../domain/hub.js"
import { FilmRepository, GroupBuyRepository, HubRepository } from "../domain/repository.js"

/**
 * groupbuy 上下文内存仓储（含 mock 种子数据）。
 * 成团优惠条件（threshold / 成团价）为与商家谈判结果的 mock 占位。
 * 商品封面为真实胶卷商品图（Wikimedia Commons 自由授权图，下载到 assets/films/*.jpg）；
 * 仅 Fujifilm PRO 400H（120）暂缺可靠商品图，仍用占位插画，后续替换。
 */

const demoImage = (i: number): SampleImage => ({
  id: `seed-demo-${i}`,
  url: `/api/groupbuy/images/demo/demo-${i}.svg`,
  uploadedBy: "seed",
})

const cover = (name: string): string => `/api/groupbuy/images/films/${name}`

const seedHubs = (now: Date): ReadonlyArray<Hub> => [
  Hub.create({
    id: makeHubId("hub-sh-ja"),
    name: "上海·静安寺点",
    city: "上海",
    address: "静安区胶州路 158 号 · 光影空间",
    createdAt: now,
  }),
  Hub.create({
    id: makeHubId("hub-sh-wjc"),
    name: "上海·五角场点",
    city: "上海",
    address: "杨浦区大学路 65 号 · 白噪咖啡",
    createdAt: now,
  }),
  Hub.create({
    id: makeHubId("hub-hz-bj"),
    name: "杭州·滨江点",
    city: "杭州",
    address: "滨江区江陵路 1916 号 · 星澜里",
    createdAt: now,
  }),
  Hub.create({
    id: makeHubId("hub-bj-wdk"),
    name: "北京·五道口点",
    city: "北京",
    address: "海淀区成府路 45 号 · 胶集",
    createdAt: now,
  }),
]

export const seedFilms = (): ReadonlyArray<Film> => [
  // ===== 135 画幅 =====
  Film.create({
    id: makeFilmId("film-kodak-gold-200-135"),
    name: "Kodak Gold 200",
    brand: "Kodak",
    format: "135",
    iso: 200,
    process: "C-41",
    coverImageUrl: cover("kodak-gold-200-135.jpg"),
    features: ["经典暖色调，肤色讨喜", "宽容度高，容错友好", "颗粒细腻", "入门性价比之王"],
    scenarios: ["日常扫街", "人像", "旅行记录"],
    sampleImages: [demoImage(1), demoImage(2), demoImage(3)],
    basePriceInCents: 5980,
    deal: { threshold: 20, groupBuyPriceInCents: 4590 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-portra-400-135"),
    name: "Kodak Portra 400",
    brand: "Kodak",
    format: "135",
    iso: 400,
    process: "C-41",
    coverImageUrl: cover("kodak-portra-400-135.jpg"),
    features: ["肤色还原自然", "颗粒极其细腻", "高感光度下依然稳定"],
    scenarios: ["人像", "婚礼", "弱光环境"],
    sampleImages: [demoImage(1), demoImage(2)],
    basePriceInCents: 9580,
    deal: { threshold: 30, groupBuyPriceInCents: 7990 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-ektar-100-135"),
    name: "Kodak Ektar 100",
    brand: "Kodak",
    format: "135",
    iso: 100,
    process: "C-41",
    coverImageUrl: cover("kodak-ektar-100-135.jpg"),
    features: ["色彩饱和浓郁", "颗粒极细", "锐度高"],
    scenarios: ["风光", "建筑", "晴天人像"],
    sampleImages: [demoImage(1), demoImage(3)],
    basePriceInCents: 6980,
    deal: { threshold: 30, groupBuyPriceInCents: 5990 },
  }),
  Film.create({
    id: makeFilmId("film-fujifilm-c200-135"),
    name: "Fujifilm C200",
    brand: "Fujifilm",
    format: "135",
    iso: 200,
    process: "C-41",
    coverImageUrl: cover("fujifilm-c200-135.jpg"),
    features: ["日系清淡色彩", "绿色表现清新", "价格亲民"],
    scenarios: ["日常记录", "风景", "美食"],
    sampleImages: [demoImage(2), demoImage(3)],
    basePriceInCents: 4380,
    deal: { threshold: 25, groupBuyPriceInCents: 3590 },
  }),
  Film.create({
    id: makeFilmId("film-ilford-hp5-135"),
    name: "Ilford HP5 Plus",
    brand: "Ilford",
    format: "135",
    iso: 400,
    process: "黑白 (D-76)",
    coverImageUrl: cover("ilford-hp5-135.jpg"),
    features: ["灰阶过渡丰富", "高宽容度", "迫冲潜力大"],
    scenarios: ["纪实", "街头摄影", "阴天弱光"],
    sampleImages: [demoImage(3), demoImage(1)],
    basePriceInCents: 5580,
    deal: { threshold: 20, groupBuyPriceInCents: 4680 },
  }),
  // ===== 120 画幅（中画幅） =====
  Film.create({
    id: makeFilmId("film-kodak-gold-200-120"),
    name: "Kodak Gold 200",
    brand: "Kodak",
    format: "120",
    iso: 200,
    process: "C-41",
    coverImageUrl: cover("kodak-gold-200-120.jpg"),
    features: ["中画幅大底片", "暖调经典，细节丰富", "宽容度高"],
    scenarios: ["中画幅扫街", "风光", "胶片入门升级"],
    sampleImages: [demoImage(1), demoImage(2)],
    basePriceInCents: 7480,
    deal: { threshold: 15, groupBuyPriceInCents: 6290 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-portra-400-120"),
    name: "Kodak Portra 400",
    brand: "Kodak",
    format: "120",
    iso: 400,
    process: "C-41",
    coverImageUrl: cover("kodak-portra-400-120.jpg"),
    features: ["6×6/6×7 细腻画质", "肤色自然", "弱光稳定"],
    scenarios: ["中画幅人像", "婚礼跟拍", "棚拍"],
    sampleImages: [demoImage(2), demoImage(3)],
    basePriceInCents: 11580,
    deal: { threshold: 15, groupBuyPriceInCents: 9890 },
  }),
  Film.create({
    id: makeFilmId("film-fujifilm-pro400h-120"),
    name: "Fujifilm PRO 400H",
    brand: "Fujifilm",
    format: "120",
    iso: 400,
    process: "C-41",
    coverImageUrl: cover("fujifilm-pro400h-120.svg"),
    description: "已于 2021 年停产，目前市场流通的是库存尾货，售完即止；想长期拍可考虑 Portra 400。",
    features: ["日系清新色调", "高光过渡柔和", "绿色表现通透"],
    scenarios: ["日系人像", "旅行", "生活记录"],
    sampleImages: [demoImage(2), demoImage(1)],
    basePriceInCents: 10880,
    deal: { threshold: 15, groupBuyPriceInCents: 9280 },
  }),
  Film.create({
    id: makeFilmId("film-ilford-hp5-120"),
    name: "Ilford HP5 Plus",
    brand: "Ilford",
    format: "120",
    iso: 400,
    process: "黑白 (D-76)",
    coverImageUrl: cover("ilford-hp5-120.jpg"),
    features: ["中画幅灰阶细腻", "高宽容度", "迫冲潜力大"],
    scenarios: ["中画幅纪实", "街头", "阴天弱光"],
    sampleImages: [demoImage(3), demoImage(2)],
    basePriceInCents: 6480,
    deal: { threshold: 15, groupBuyPriceInCents: 5490 },
  }),

  // ===== 135 补充：柯达主力线 + 富士国行 + 国货 + 创意卷 =====
  Film.create({
    id: makeFilmId("film-kodak-ultramax-400-135"),
    name: "Kodak UltraMax 400",
    brand: "Kodak",
    format: "135",
    iso: 400,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "柯达「全能 400」，室内外通吃的性价比主力卷，颜色偏冷、绿植表现讨喜。",
    features: ["400 度高感通吃", "宽容度高", "价格亲民", "新手第一卷首选"],
    scenarios: ["日常记录", "旅行", "阴天与室内"],
    sampleImages: [demoImage(1), demoImage(3)],
    basePriceInCents: 5500,
    deal: { threshold: 24, groupBuyPriceInCents: 4250 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-portra-160-135"),
    name: "Kodak Portra 160",
    brand: "Kodak",
    format: "135",
    iso: 160,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "Portra 系列最低感光的一支，颗粒最细，适合晴天与棚拍人像。",
    features: ["颗粒极细", "肤色奶油感", "扫描友好"],
    scenarios: ["晴天户外人像", "棚拍", "静物"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 9800,
    deal: { threshold: 15, groupBuyPriceInCents: 7900 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-portra-800-135"),
    name: "Kodak Portra 800",
    brand: "Kodak",
    format: "135",
    iso: 800,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "夜拍与舞台光的救星，高感下依然保持柔和肤色。",
    features: ["高感光夜拍", "肤色依然柔和", "迫冲到 1600 可用"],
    scenarios: ["夜景", "婚礼跟拍", "室内弱光"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 14500,
    deal: { threshold: 12, groupBuyPriceInCents: 11800 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-tmax-100-135"),
    name: "Kodak T-MAX 100",
    brand: "Kodak",
    format: "135",
    iso: 100,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "现代黑白标杆：锐度极高、灰阶层次丰富，适合放大输出。",
    features: ["锐度极高", "灰阶层次丰富", "适合放大"],
    scenarios: ["风光", "建筑", "黑白人像"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 8800,
    deal: { threshold: 15, groupBuyPriceInCents: 6900 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-trix-400-135"),
    name: "Kodak Tri-X 400",
    brand: "Kodak",
    format: "135",
    iso: 400,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "七十多年历史的传奇黑白卷，粗颗粒与高反差是它的招牌味道。",
    features: ["经典粗颗粒", "反差强烈", "纪实味道浓"],
    scenarios: ["街头纪实", "新闻摄影", "弱光黑白"],
    sampleImages: [demoImage(2), demoImage(3)],
    basePriceInCents: 9200,
    deal: { threshold: 15, groupBuyPriceInCents: 7200 },
  }),
  Film.create({
    id: makeFilmId("film-fujifilm-c400-135"),
    name: "Fujifilm C400",
    brand: "Fujifilm",
    format: "135",
    iso: 400,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "富士国行复产的高感负片（原 X-TRA 400 配方路线），性能均衡，拼团性价比高。",
    features: ["色彩清爽", "高感表现稳", "国行新鲜批次"],
    scenarios: ["日常记录", "旅行", "弱光环境"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 5500,
    deal: { threshold: 24, groupBuyPriceInCents: 4250 },
  }),
  Film.create({
    id: makeFilmId("film-ilford-fp4-125-135"),
    name: "Ilford FP4 Plus 125",
    brand: "Ilford",
    format: "135",
    iso: 125,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "依尔福中速黑白，细腻且宽容，是暗房入门最友好的卷之一。",
    features: ["颗粒细腻", "宽容度高", "暗房放大友好"],
    scenarios: ["风光", "静物", "暗房练习"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 6200,
    deal: { threshold: 18, groupBuyPriceInCents: 4800 },
  }),
  Film.create({
    id: makeFilmId("film-lucky-c200-135"),
    name: "乐凯 Lucky C200",
    brand: "乐凯 Lucky",
    format: "135",
    iso: 200,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "国货之光，2026 年复产的 135 彩色负片，价格门槛最低，适合练手试机。",
    features: ["国货新复产", "价格门槛低", "练手不心疼"],
    scenarios: ["新手试机", "日常练习", "大量拍摄"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 3800,
    deal: { threshold: 30, groupBuyPriceInCents: 2900 },
  }),
  Film.create({
    id: makeFilmId("film-shanghai-gp3-100-135"),
    name: "上海 GP3 100",
    brand: "上海 ShangHai",
    format: "135",
    iso: 100,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "老牌国货黑白卷，市面最便宜的选择之一，适合试机和黑白入门。",
    features: ["价格极低", "国货情怀", "试机首选"],
    scenarios: ["试机", "黑白入门", "大量练习"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 2800,
    deal: { threshold: 40, groupBuyPriceInCents: 2200 },
  }),
  Film.create({
    id: makeFilmId("film-cinestill-800t-135"),
    name: "CineStill 800T",
    brand: "CineStill",
    format: "135",
    iso: 800,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "电影卷改制的钨丝灯平衡负片，招牌的红色光晕让它成为夜景氛围神器。",
    features: ["标志性红色光晕", "夜拍氛围感强", "电影感色调"],
    scenarios: ["夜景霓虹", "城市夜拍", "人像氛围"],
    sampleImages: [demoImage(1), demoImage(2)],
    basePriceInCents: 12800,
    deal: { threshold: 12, groupBuyPriceInCents: 9900 },
  }),

  // ===== 120 补充：专业线 + 国货 + 创意卷 =====
  Film.create({
    id: makeFilmId("film-kodak-portra-160-120"),
    name: "Kodak Portra 160",
    brand: "Kodak",
    format: "120",
    iso: 160,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "中画幅最常用的日常专业卷，颗粒细腻、肤色讨喜，晴天户外首选。",
    features: ["中画幅细腻画质", "肤色自然", "扫描友好"],
    scenarios: ["户外人像", "婚礼", "旅行记录"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 12800,
    deal: { threshold: 12, groupBuyPriceInCents: 9900 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-ektar-100-120"),
    name: "Kodak Ektar 100",
    brand: "Kodak",
    format: "120",
    iso: 100,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "色彩饱和浓郁、颗粒极细，中画幅风光的常青选择。",
    features: ["色彩浓郁", "颗粒极细", "锐度高"],
    scenarios: ["中画幅风光", "建筑", "晴天户外"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 11500,
    deal: { threshold: 12, groupBuyPriceInCents: 8800 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-tmax-100-120"),
    name: "Kodak T-MAX 100",
    brand: "Kodak",
    format: "120",
    iso: 100,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "中画幅黑白的高锐度代表，层次丰富，适合大尺寸放大。",
    features: ["锐度极高", "灰阶层次丰富", "适合放大输出"],
    scenarios: ["中画幅风光", "黑白人像", "建筑"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 11800,
    deal: { threshold: 12, groupBuyPriceInCents: 9200 },
  }),
  Film.create({
    id: makeFilmId("film-ilford-fp4-125-120"),
    name: "Ilford FP4 Plus 125",
    brand: "Ilford",
    format: "120",
    iso: 125,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "中画幅中速黑白，细腻稳定，暗房放大表现优秀。",
    features: ["颗粒细腻", "宽容度高", "暗房友好"],
    scenarios: ["中画幅风光", "静物", "暗房练习"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 7800,
    deal: { threshold: 15, groupBuyPriceInCents: 6000 },
  }),
  Film.create({
    id: makeFilmId("film-shanghai-gp3-100-120"),
    name: "上海 GP3 100",
    brand: "上海 ShangHai",
    format: "120",
    iso: 100,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "目前最便宜的 120 黑白卷之一，用来给新到手的中画幅相机试机最划算。",
    features: ["价格极低", "国货情怀", "试机不心疼"],
    scenarios: ["中画幅试机", "黑白入门", "大量练习"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 3400,
    deal: { threshold: 30, groupBuyPriceInCents: 2600 },
  }),
  Film.create({
    id: makeFilmId("film-lomography-color100-120"),
    name: "Lomography Color Negative 100",
    brand: "Lomography",
    format: "120",
    iso: 100,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "Lomography 中画幅入门负片，色彩偏暖，价格友好，适合日常随拍。",
    features: ["暖调色彩", "价格友好", "日常随拍"],
    scenarios: ["日常记录", "旅行", "朋友聚会"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 6800,
    deal: { threshold: 15, groupBuyPriceInCents: 5200 },
  }),
  Film.create({
    id: makeFilmId("film-cinestill-800t-120"),
    name: "CineStill 800T",
    brand: "CineStill",
    format: "120",
    iso: 800,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "电影卷改制的中画幅夜拍卷，红色光晕 + 大底片 = 氛围感拉满。",
    features: ["标志性红色光晕", "中画幅夜拍", "电影感色调"],
    scenarios: ["城市夜景", "人像氛围", "霓虹街拍"],
    sampleImages: [demoImage(1), demoImage(3)],
    basePriceInCents: 15800,
    deal: { threshold: 10, groupBuyPriceInCents: 12200 },
  }),

  // ===== 135 第三批：柯达全线 + 富士反转片 + 依尔福全家桶 + 入门黑白 + 创意卷 =====
  Film.create({
    id: makeFilmId("film-kodak-colorplus-200-135"),
    name: "Kodak ColorPlus 200",
    brand: "Kodak",
    format: "135",
    iso: 200,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "柯达最便宜的彩负之一，色调偏暖，日常练手性价比之选。",
    features: ["价格亲民", "暖调色彩", "练手友好"],
    scenarios: ["日常记录", "旅行", "新手练习"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 4700,
    deal: { threshold: 20, groupBuyPriceInCents: 3690 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-proimage-100-135"),
    name: "Kodak ProImage 100",
    brand: "Kodak",
    format: "135",
    iso: 100,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "亚洲市场专供的人像卷，肤色柔和、颗粒细腻，价格却很友好。",
    features: ["肤色柔和", "颗粒细腻", "亚洲专供"],
    scenarios: ["人像", "婚礼", "户外记录"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 4900,
    deal: { threshold: 20, groupBuyPriceInCents: 3890 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-tmax-400-135"),
    name: "Kodak T-MAX 400",
    brand: "Kodak",
    format: "135",
    iso: 400,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "现代感最强的黑白 400 度，颗粒细腻、层次丰富，迫冲到 1600 表现依然稳。",
    features: ["颗粒细腻", "迫冲潜力大", "现代黑白标杆"],
    scenarios: ["纪实", "弱光黑白", "人像"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 9500,
    deal: { threshold: 15, groupBuyPriceInCents: 7400 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-ektachrome-e100-135"),
    name: "Kodak Ektachrome E100",
    brand: "Kodak",
    format: "135",
    iso: 100,
    process: "E-6 (反转片)",
    coverImageUrl: cover("placeholder.svg"),
    description: "柯达目前在产的主力反转片，色彩真实细腻，适合追求直出观感的风光党。",
    features: ["色彩还原真实", "颗粒极细", "直出即成品"],
    scenarios: ["风光", "静物", "翻拍"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 15800,
    deal: { threshold: 12, groupBuyPriceInCents: 12500 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-vision3-250d-135"),
    name: "Kodak Vision3 250D",
    brand: "Kodak",
    format: "135",
    iso: 250,
    process: "ECN-2 / C-41 兼容",
    coverImageUrl: cover("placeholder.svg"),
    description: "电影卷 5207 分装，好莱坞级别的色彩科学，日光平衡，画面自带电影感。",
    features: ["电影感色调", "高光宽容度极佳", "分装价格友好"],
    scenarios: ["日常扫街", "风光", "视频感画面"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 6500,
    deal: { threshold: 20, groupBuyPriceInCents: 4990 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-vision3-500t-135"),
    name: "Kodak Vision3 500T",
    brand: "Kodak",
    format: "135",
    iso: 500,
    process: "ECN-2 / C-41 兼容",
    coverImageUrl: cover("placeholder.svg"),
    description: "电影卷 5219（诺兰同款生产线），灯光平衡，夜拍党最爱，销量常年霸榜。",
    features: ["夜拍表现极佳", "电影感浓郁", "销量常年霸榜"],
    scenarios: ["夜景", "室内灯光", "城市扫街"],
    sampleImages: [demoImage(3), demoImage(1)],
    basePriceInCents: 7200,
    deal: { threshold: 18, groupBuyPriceInCents: 5580 },
  }),
  Film.create({
    id: makeFilmId("film-fujifilm-velvia-50-135"),
    name: "Fujifilm Velvia 50",
    brand: "Fujifilm",
    format: "135",
    iso: 50,
    process: "E-6 (反转片)",
    coverImageUrl: cover("placeholder.svg"),
    description: "风光摄影传奇反转片，色彩浓烈到发光。已停产但按订单限量复产，2026 年国内重新上架，¥338/卷。",
    features: ["色彩浓烈", "风光传奇", "限量稀缺"],
    scenarios: ["风光", "日出日落", "花卉"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 33800,
    deal: { threshold: 8, groupBuyPriceInCents: 29800 },
  }),
  Film.create({
    id: makeFilmId("film-fujifilm-provia-100f-135"),
    name: "Fujifilm Provia 100F",
    brand: "Fujifilm",
    format: "135",
    iso: 100,
    process: "E-6 (反转片)",
    coverImageUrl: cover("placeholder.svg"),
    description: "富士反转片常青树，中性锐利。已停产但按订单限量复产，¥288/卷。",
    features: ["中性锐利", "颗粒极细", "限量稀缺"],
    scenarios: ["风光", "建筑", "微距"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 28800,
    deal: { threshold: 8, groupBuyPriceInCents: 25800 },
  }),
  Film.create({
    id: makeFilmId("film-ilford-delta-400-135"),
    name: "Ilford Delta 400",
    brand: "Ilford",
    format: "135",
    iso: 400,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "依尔福高感黑白主力，层次比 HP5 更锐，弱光纪实的好搭档。",
    features: ["高感黑白", "层次锐利", "弱光稳定"],
    scenarios: ["纪实", "弱光环境", "街头"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 7400,
    deal: { threshold: 15, groupBuyPriceInCents: 5800 },
  }),
  Film.create({
    id: makeFilmId("film-ilford-xp2-super-400-135"),
    name: "Ilford XP2 Super 400",
    brand: "Ilford",
    format: "135",
    iso: 400,
    process: "C-41 (染料黑白)",
    coverImageUrl: cover("placeholder.svg"),
    description: "C-41 工艺的黑白卷：任何彩扩店都能冲，黑白党的省心之选。",
    features: ["C-41 通用冲洗", "颗粒细腻", "便利店也能冲"],
    scenarios: ["黑白入门", "旅行记录", "日常随拍"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 6600,
    deal: { threshold: 15, groupBuyPriceInCents: 5200 },
  }),
  Film.create({
    id: makeFilmId("film-ilford-panf-plus-50-135"),
    name: "Ilford Pan F Plus 50",
    brand: "Ilford",
    format: "135",
    iso: 50,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "ISO 50 的超细颗粒黑白，放大后如刀锐利，慢工出细活的选择。",
    features: ["超细颗粒", "极致锐度", "日光大光圈"],
    scenarios: ["风光", "建筑", "静物"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 5900,
    deal: { threshold: 18, groupBuyPriceInCents: 4600 },
  }),
  Film.create({
    id: makeFilmId("film-kentmere-400-135"),
    name: "Kentmere 400",
    brand: "Kentmere",
    format: "135",
    iso: 400,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "依尔福旗下入门品牌，最便宜的进口黑白卷，大量拍不心疼。",
    features: ["价格极低", "依尔福品质", "大量练习"],
    scenarios: ["试机", "暗房练习", "日常扫街"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 3900,
    deal: { threshold: 30, groupBuyPriceInCents: 3000 },
  }),
  Film.create({
    id: makeFilmId("film-foma-fomapan-200-135"),
    name: "Foma Fomapan 200",
    brand: "Foma",
    format: "135",
    iso: 200,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "捷克老厂的经典黑白，颗粒复古、反差经典，价格友好。",
    features: ["复古颗粒", "价格友好", "经典反差"],
    scenarios: ["黑白入门", "扫街", "日常练习"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 3300,
    deal: { threshold: 30, groupBuyPriceInCents: 2600 },
  }),
  Film.create({
    id: makeFilmId("film-rollei-rpx-400-135"),
    name: "Rollei RPX 400",
    brand: "Rollei",
    format: "135",
    iso: 400,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "德国牌（爱克发产线）经典黑白，反差与层次平衡，德味选择。",
    features: ["德系风格", "反差平衡", "价格友好"],
    scenarios: ["纪实", "人像", "扫街"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 4600,
    deal: { threshold: 20, groupBuyPriceInCents: 3600 },
  }),
  Film.create({
    id: makeFilmId("film-lomography-cn400-135"),
    name: "Lomography Color Negative 400",
    brand: "Lomography",
    format: "135",
    iso: 400,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "乐摸高感彩负，色彩浓郁鲜活，LOMO 玩法的百搭底卷。",
    features: ["色彩浓郁", "高感通吃", "LOMO 玩法百搭"],
    scenarios: ["日常随拍", "派对", "旅行"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 5900,
    deal: { threshold: 20, groupBuyPriceInCents: 4600 },
  }),
  Film.create({
    id: makeFilmId("film-lomochrome-purple-135"),
    name: "Lomography LomoChrome Purple",
    brand: "Lomography",
    format: "135",
    iso: 400,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "小红书网红「紫卷」：绿色变紫、蓝色变青的魔法卷，随手拍都很出片。",
    features: ["网红紫色调", "随手出片", "社交媒体友好"],
    scenarios: ["创意拍摄", "人像氛围", "风光玩色"],
    sampleImages: [demoImage(1), demoImage(2)],
    basePriceInCents: 9900,
    deal: { threshold: 12, groupBuyPriceInCents: 7900 },
  }),
  Film.create({
    id: makeFilmId("film-cinestill-50d-135"),
    name: "CineStill 50D",
    brand: "CineStill",
    format: "135",
    iso: 50,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "日光电影卷，极其细腻锐利，晴天大光圈党最爱。",
    features: ["超细腻锐利", "日光电影感", "白天大光圈"],
    scenarios: ["晴天扫街", "风光", "人像"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 11900,
    deal: { threshold: 12, groupBuyPriceInCents: 9200 },
  }),
  Film.create({
    id: makeFilmId("film-cinestill-400d-135"),
    name: "CineStill 400D",
    brand: "CineStill",
    format: "135",
    iso: 400,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "最新的日光电影卷，兼顾 800T 的电影感与日光平衡，C-41 直冲。",
    features: ["电影感", "日光平衡", "C-41 直冲"],
    scenarios: ["日常扫街", "旅行", "人像"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 12600,
    deal: { threshold: 12, groupBuyPriceInCents: 9800 },
  }),

  // ===== 120 第三批：黑白主力 + 反转片 + 电影卷 =====
  Film.create({
    id: makeFilmId("film-kodak-tmax-400-120"),
    name: "Kodak T-MAX 400",
    brand: "Kodak",
    format: "120",
    iso: 400,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "中画幅高感黑白，夜拍手持可行，放大输出素质极高。",
    features: ["中画幅高感", "颗粒细腻", "放大素质高"],
    scenarios: ["中画幅纪实", "弱光环境", "黑白人像"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 12200,
    deal: { threshold: 12, groupBuyPriceInCents: 9500 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-ektachrome-e100-120"),
    name: "Kodak Ektachrome E100",
    brand: "Kodak",
    format: "120",
    iso: 100,
    process: "E-6 (反转片)",
    coverImageUrl: cover("placeholder.svg"),
    description: "中画幅反转片直出即巅峰，灯箱观片或高端扫描的终极选择。",
    features: ["反转片直出", "色彩真实", "灯箱观片"],
    scenarios: ["中画幅风光", "静物", "微距"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 17500,
    deal: { threshold: 10, groupBuyPriceInCents: 13900 },
  }),
  Film.create({
    id: makeFilmId("film-fujifilm-velvia-50-120"),
    name: "Fujifilm Velvia 50",
    brand: "Fujifilm",
    format: "120",
    iso: 50,
    process: "E-6 (反转片)",
    coverImageUrl: cover("placeholder.svg"),
    description: "中画幅风光的传奇答案，浓烈色彩 + 大底片，冲灯箱的那一刻一切都值。已停产，库存稀缺。",
    features: ["色彩浓烈", "风光传奇", "库存稀缺"],
    scenarios: ["中画幅风光", "日出日落", "花卉"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 38800,
    deal: { threshold: 8, groupBuyPriceInCents: 33800 },
  }),
  Film.create({
    id: makeFilmId("film-ilford-delta-100-120"),
    name: "Ilford Delta 100",
    brand: "Ilford",
    format: "120",
    iso: 100,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "中画幅细颗粒黑白之王，层次丰富到可以数得清，风光与建筑首选。",
    features: ["细颗粒之王", "层次极丰富", "放大友好"],
    scenarios: ["中画幅风光", "建筑", "黑白人像"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 8600,
    deal: { threshold: 12, groupBuyPriceInCents: 6800 },
  }),
  Film.create({
    id: makeFilmId("film-ilford-xp2-super-400-120"),
    name: "Ilford XP2 Super 400",
    brand: "Ilford",
    format: "120",
    iso: 400,
    process: "C-41 (染料黑白)",
    coverImageUrl: cover("placeholder.svg"),
    description: "C-41 工艺的中画幅黑白，彩扩店直接冲，中画幅黑白的省心方案。",
    features: ["C-41 通用冲洗", "颗粒细腻", "省心之选"],
    scenarios: ["中画幅黑白入门", "旅行", "日常记录"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 8900,
    deal: { threshold: 12, groupBuyPriceInCents: 6900 },
  }),
  Film.create({
    id: makeFilmId("film-foma-fomapan-200-120"),
    name: "Foma Fomapan 200",
    brand: "Foma",
    format: "120",
    iso: 200,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "最便宜的中画幅黑白之一，复古颗粒，试机与练习首选。",
    features: ["价格极低", "复古颗粒", "试机首选"],
    scenarios: ["中画幅试机", "黑白练习", "日常扫街"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 4600,
    deal: { threshold: 20, groupBuyPriceInCents: 3600 },
  }),
  Film.create({
    id: makeFilmId("film-cinestill-400d-120"),
    name: "CineStill 400D",
    brand: "CineStill",
    format: "120",
    iso: 400,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "中画幅电影卷，日光平衡 + 电影感色调，大底片氛围天花板。",
    features: ["电影感色调", "日光平衡", "中画幅氛围"],
    scenarios: ["中画幅日常", "人像", "旅行"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 13800,
    deal: { threshold: 10, groupBuyPriceInCents: 10900 },
  }),

  // ===== 135 第四批：黑白深度 + 电影卷 + 创意卷 =====
  Film.create({
    id: makeFilmId("film-fujifilm-acros-ii-100-135"),
    name: "Fujifilm Neopan ACROS II 100",
    brand: "Fujifilm",
    format: "135",
    iso: 100,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "富士专业黑白主力（停产改配方后重生），极细颗粒 + 强反差，黑白党的必拍清单。",
    features: ["极细颗粒", "反差强烈", "长曝光倒易律优秀"],
    scenarios: ["风光", "长曝光", "黑白人像"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 9200,
    deal: { threshold: 15, groupBuyPriceInCents: 7200 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-vision3-50d-135"),
    name: "Kodak Vision3 50D",
    brand: "Kodak",
    format: "135",
    iso: 50,
    process: "ECN-2 / C-41 兼容",
    coverImageUrl: cover("placeholder.svg"),
    description: "电影卷里最细腻的一支，日光低感，白天户外细节保留到极致。",
    features: ["极致细腻", "日光电影感", "大光圈白天拍"],
    scenarios: ["晴天扫街", "风光", "人像"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 6800,
    deal: { threshold: 18, groupBuyPriceInCents: 5300 },
  }),
  Film.create({
    id: makeFilmId("film-ilford-delta-3200-135"),
    name: "Ilford Delta 3200",
    brand: "Ilford",
    format: "135",
    iso: 3200,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "依尔福超高速黑白，弱光手持与现场光纪实神器，粗颗粒就是它的味道。",
    features: ["ISO 3200 超高速", "弱光手持", "粗颗粒味道"],
    scenarios: ["夜拍", "现场光纪实", "演出舞台"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 8800,
    deal: { threshold: 12, groupBuyPriceInCents: 6900 },
  }),
  Film.create({
    id: makeFilmId("film-kentmere-100-135"),
    name: "Kentmere 100",
    brand: "Kentmere",
    format: "135",
    iso: 100,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "依尔福旗下入门黑白 100 度，晴天下最细腻的廉价选择。",
    features: ["价格极低", "细颗粒", "暗房练习"],
    scenarios: ["晴天扫街", "静物", "暗房入门"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 3900,
    deal: { threshold: 30, groupBuyPriceInCents: 3000 },
  }),
  Film.create({
    id: makeFilmId("film-foma-fomapan-100-135"),
    name: "Foma Fomapan 100",
    brand: "Foma",
    format: "135",
    iso: 100,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "捷克入门黑白，反差柔和、宽容度高，廉价却不廉价感。",
    features: ["价格友好", "反差柔和", "宽容度高"],
    scenarios: ["黑白入门", "扫街", "大量练习"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 3300,
    deal: { threshold: 30, groupBuyPriceInCents: 2600 },
  }),
  Film.create({
    id: makeFilmId("film-rollei-rpx-100-135"),
    name: "Rollei RPX 100",
    brand: "Rollei",
    format: "135",
    iso: 100,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "德国牌（爱克发产线）中速黑白，经典德味影调，价格友好。",
    features: ["德系影调", "细颗粒", "价格友好"],
    scenarios: ["风光", "人像", "日常记录"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 4600,
    deal: { threshold: 20, groupBuyPriceInCents: 3600 },
  }),
  Film.create({
    id: makeFilmId("film-adox-silvermax-100-135"),
    name: "Adox Silvermax 100",
    brand: "Adox",
    format: "135",
    iso: 100,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "广告片级含银量最高的黑白卷，反差强烈、银盐质感独特，黑白玩家的进阶之选。",
    features: ["高含银量", "反差强烈", "银盐质感独特"],
    scenarios: ["黑白创作", "风光", "人像"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 10800,
    deal: { threshold: 12, groupBuyPriceInCents: 8500 },
  }),
  Film.create({
    id: makeFilmId("film-lomography-earlgrey-100-135"),
    name: "Lomography Earl Grey 100",
    brand: "Lomography",
    format: "135",
    iso: 100,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "乐摸黑白卷，中速经典影调、价格友好，日常拍黑白不心疼。",
    features: ["经典黑白影调", "价格友好", "日常不心疼"],
    scenarios: ["日常黑白", "扫街", "暗房练习"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 5200,
    deal: { threshold: 20, groupBuyPriceInCents: 4100 },
  }),
  Film.create({
    id: makeFilmId("film-lomochrome-turquoise-135"),
    name: "Lomography LomoChrome Turquoise",
    brand: "Lomography",
    format: "135",
    iso: 100,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "「青卷」：红色变绿、蓝色变青的魔法配色，和紫卷并称创意双雄。",
    features: ["网红青色调", "随手出片", "创意玩法"],
    scenarios: ["创意拍摄", "人像氛围", "风光玩色"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 9900,
    deal: { threshold: 12, groupBuyPriceInCents: 7900 },
  }),
  Film.create({
    id: makeFilmId("film-jch-streetpan-400-135"),
    name: "JCH StreetPan 400",
    brand: "JCH",
    format: "135",
    iso: 400,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "街拍党口碑卷（依尔福产线代工），超高感红光敏感，夜街拍的黑白利器。",
    features: ["超高感红光敏感", "粗颗粒街拍味", "夜街拍利器"],
    scenarios: ["街头纪实", "夜拍", "现场光"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 6800,
    deal: { threshold: 15, groupBuyPriceInCents: 5300 },
  }),

  // ===== 120 第四批：黑白主力 + 专业负片 + 创意卷 =====
  Film.create({
    id: makeFilmId("film-fujifilm-acros-ii-100-120"),
    name: "Fujifilm Neopan ACROS II 100",
    brand: "Fujifilm",
    format: "120",
    iso: 100,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "中画幅版 ACROS II：极细颗粒配大底片，风光黑白的天花板组合。",
    features: ["中画幅极细颗粒", "反差强烈", "长曝光优秀"],
    scenarios: ["中画幅风光", "长曝光", "黑白创作"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 12500,
    deal: { threshold: 12, groupBuyPriceInCents: 9800 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-trix-400-120"),
    name: "Kodak Tri-X 400",
    brand: "Kodak",
    format: "120",
    iso: 400,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "传奇黑白卷的中画幅版本，粗颗粒 + 大底片，纪实味道更浓。",
    features: ["经典粗颗粒", "中画幅纪实", "反差强烈"],
    scenarios: ["中画幅纪实", "街头", "黑白人像"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 12200,
    deal: { threshold: 12, groupBuyPriceInCents: 9500 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-portra-800-120"),
    name: "Kodak Portra 800",
    brand: "Kodak",
    format: "120",
    iso: 800,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "中画幅高感专业卷，婚礼、夜拍、室内弱光全靠它撑场。",
    features: ["中画幅高感", "肤色柔和", "弱光稳定"],
    scenarios: ["婚礼跟拍", "夜拍", "室内人像"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 17800,
    deal: { threshold: 10, groupBuyPriceInCents: 14200 },
  }),
  Film.create({
    id: makeFilmId("film-foma-fomapan-100-120"),
    name: "Foma Fomapan 100",
    brand: "Foma",
    format: "120",
    iso: 100,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "最便宜的中画幅黑白之一，反差柔和，练手与试机的好选择。",
    features: ["价格极低", "反差柔和", "试机首选"],
    scenarios: ["中画幅试机", "黑白练习", "日常扫街"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 4600,
    deal: { threshold: 20, groupBuyPriceInCents: 3600 },
  }),
  Film.create({
    id: makeFilmId("film-rollei-rpx-100-120"),
    name: "Rollei RPX 100",
    brand: "Rollei",
    format: "120",
    iso: 100,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "德系中速黑白中画幅版，细颗粒与宽容度兼顾。",
    features: ["德系影调", "细颗粒", "价格友好"],
    scenarios: ["中画幅风光", "人像", "日常记录"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 5900,
    deal: { threshold: 15, groupBuyPriceInCents: 4600 },
  }),
  Film.create({
    id: makeFilmId("film-lomography-cn400-120"),
    name: "Lomography Color Negative 400",
    brand: "Lomography",
    format: "120",
    iso: 400,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "中画幅高感彩负，色彩浓郁鲜活，LOMO 中画幅的日常底卷。",
    features: ["色彩浓郁", "高感通吃", "价格友好"],
    scenarios: ["中画幅日常", "旅行", "派对"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 7800,
    deal: { threshold: 15, groupBuyPriceInCents: 6000 },
  }),
  Film.create({
    id: makeFilmId("film-lomochrome-purple-120"),
    name: "Lomography LomoChrome Purple",
    brand: "Lomography",
    format: "120",
    iso: 400,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "中画幅「紫卷」：绿色变紫、蓝色变青，大底片 + 魔幻配色，出片即爆款。",
    features: ["网红紫色调", "中画幅魔幻配色", "社交媒体友好"],
    scenarios: ["创意拍摄", "中画幅人像", "风光玩色"],
    sampleImages: [demoImage(1), demoImage(2)],
    basePriceInCents: 11800,
    deal: { threshold: 10, groupBuyPriceInCents: 9500 },
  }),
]

const persistence = <A, E>(self: Effect.Effect<A, E>): Effect.Effect<A, PersistenceError> =>
  self.pipe(
    Effect.mapError((e) =>
      new PersistenceError({ message: e instanceof Error ? e.message : String(e) }),
    ),
  )

export const HubRepositoryInMemory = Layer.effect(
  HubRepository,
  Effect.gen(function* () {
    const store = yield* Ref.make(new Map<string, Hub>(seedHubs(new Date()).map((h) => [h.id, h])))
    return HubRepository.make({
      findAll: () => persistence(Ref.get(store).pipe(Effect.map((m) => [...m.values()]))),
      findById: (id: HubId) =>
        persistence(Ref.get(store).pipe(Effect.map((m) => Option.fromNullable(m.get(id))))),
      save: (hub: Hub) => persistence(Ref.update(store, (m) => m.set(hub.id, hub))),
    })
  }),
)

export const FilmRepositoryInMemory = Layer.effect(
  FilmRepository,
  Effect.gen(function* () {
    const store = yield* Ref.make(new Map<string, Film>(seedFilms().map((f) => [f.id, f])))
    return FilmRepository.make({
      findAll: () => persistence(Ref.get(store).pipe(Effect.map((m) => [...m.values()]))),
      findById: (id: FilmId) =>
        persistence(Ref.get(store).pipe(Effect.map((m) => Option.fromNullable(m.get(id))))),
      save: (film: Film) => persistence(Ref.update(store, (m) => m.set(film.id, film))),
    })
  }),
)

export const GroupBuyRepositoryInMemory = Layer.effect(
  GroupBuyRepository,
  Effect.gen(function* () {
    const store = yield* Ref.make(new Map<string, GroupBuy>())
    const keyOf = (hubId: HubId, filmId: FilmId): string => `${hubId}::${filmId}`
    return GroupBuyRepository.make({
      findByHubAndFilm: (hubId: HubId, filmId: FilmId) =>
        persistence(
          Ref.get(store).pipe(Effect.map((m) => Option.fromNullable(m.get(keyOf(hubId, filmId))))),
        ),
      save: (group: GroupBuy) =>
        persistence(Ref.update(store, (m) => m.set(keyOf(group.hubId, group.filmId), group))),
    })
  }),
)
