import { Effect, Layer, Option, Ref } from "effect"

import { PersistenceError } from "../../../shared/errors.js"
import type { SampleImage , FilmId} from "../domain/film.js"
import { Film, makeFilmId } from "../domain/film.js"
import type { GroupBuy } from "../domain/groupBuy.js"
import type { HubId } from "../domain/hub.js"
import { Hub, makeHubId } from "../domain/hub.js"
import { FilmRepository, GroupBuyRepository, HubRepository } from "../domain/repository.js"

/**
 * groupbuy 上下文内存仓储（含 mock 种子数据）。
 * 成团优惠条件（threshold / 成团价）为与商家谈判结果的 mock 占位。
 * 商品封面为真实胶卷商品图（Wikimedia Commons 自由授权图，下载到 assets/films/*.jpg）；
 * 仅 Fujifilm PRO 400H（120）暂缺可靠商品图，仍用占位插画，后续替换。
 */

const demoImage = (i: number): SampleImage => ({
  id: `seed-demo-${i}`,
  url: `/api/groupbuy/images/demo/demo-${i}.svg`,
  uploadedBy: "seed",
})

const cover = (name: string): string => `/api/groupbuy/images/films/${name}`

const seedHubs = (now: Date): ReadonlyArray<Hub> => [
  Hub.create({
    id: makeHubId("hub-sh-ja"),
    name: "上海·静安寺点",
    city: "上海",
    address: "静安区胶州路 158 号 · 光影空间",
    createdAt: now,
  }),
  Hub.create({
    id: makeHubId("hub-sh-wjc"),
    name: "上海·五角场点",
    city: "上海",
    address: "杨浦区大学路 65 号 · 白噪咖啡",
    createdAt: now,
  }),
  Hub.create({
    id: makeHubId("hub-hz-bj"),
    name: "杭州·滨江点",
    city: "杭州",
    address: "滨江区江陵路 1916 号 · 星澜里",
    createdAt: now,
  }),
  Hub.create({
    id: makeHubId("hub-bj-wdk"),
    name: "北京·五道口点",
    city: "北京",
    address: "海淀区成府路 45 号 · 胶集",
    createdAt: now,
  }),
]

export const seedFilms = (): ReadonlyArray<Film> => [
  // ===== 135 画幅 =====
  Film.create({
    id: makeFilmId("film-kodak-gold-200-135"),
    name: "Kodak Gold 200",
    brand: "Kodak",
    format: "135",
    iso: 200,
    process: "C-41",
    coverImageUrl: cover("kodak-gold-200-135.jpg"),
    features: ["经典暖色调，肤色讨喜", "宽容度高，容错友好", "颗粒细腻", "入门性价比之王"],
    scenarios: ["日常扫街", "人像", "旅行记录"],
    sampleImages: [demoImage(1), demoImage(2), demoImage(3)],
    basePriceInCents: 5980,
    deal: { threshold: 20, groupBuyPriceInCents: 4590 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-portra-400-135"),
    name: "Kodak Portra 400",
    brand: "Kodak",
    format: "135",
    iso: 400,
    process: "C-41",
    coverImageUrl: cover("kodak-portra-400-135.jpg"),
    features: ["肤色还原自然", "颗粒极其细腻", "高感光度下依然稳定"],
    scenarios: ["人像", "婚礼", "弱光环境"],
    sampleImages: [demoImage(1), demoImage(2)],
    basePriceInCents: 9580,
    deal: { threshold: 30, groupBuyPriceInCents: 7990 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-ektar-100-135"),
    name: "Kodak Ektar 100",
    brand: "Kodak",
    format: "135",
    iso: 100,
    process: "C-41",
    coverImageUrl: cover("kodak-ektar-100-135.jpg"),
    features: ["色彩饱和浓郁", "颗粒极细", "锐度高"],
    scenarios: ["风光", "建筑", "晴天人像"],
    sampleImages: [demoImage(1), demoImage(3)],
    basePriceInCents: 6980,
    deal: { threshold: 30, groupBuyPriceInCents: 5990 },
  }),
  Film.create({
    id: makeFilmId("film-fujifilm-c200-135"),
    name: "Fujifilm C200",
    brand: "Fujifilm",
    format: "135",
    iso: 200,
    process: "C-41",
    coverImageUrl: cover("fujifilm-c200-135.jpg"),
    features: ["日系清淡色彩", "绿色表现清新", "价格亲民"],
    scenarios: ["日常记录", "风景", "美食"],
    sampleImages: [demoImage(2), demoImage(3)],
    basePriceInCents: 4380,
    deal: { threshold: 25, groupBuyPriceInCents: 3590 },
  }),
  Film.create({
    id: makeFilmId("film-ilford-hp5-135"),
    name: "Ilford HP5 Plus",
    brand: "Ilford",
    format: "135",
    iso: 400,
    process: "黑白 (D-76)",
    coverImageUrl: cover("ilford-hp5-135.jpg"),
    features: ["灰阶过渡丰富", "高宽容度", "迫冲潜力大"],
    scenarios: ["纪实", "街头摄影", "阴天弱光"],
    sampleImages: [demoImage(3), demoImage(1)],
    basePriceInCents: 5580,
    deal: { threshold: 20, groupBuyPriceInCents: 4680 },
  }),
  // ===== 120 画幅（中画幅） =====
  Film.create({
    id: makeFilmId("film-kodak-gold-200-120"),
    name: "Kodak Gold 200",
    brand: "Kodak",
    format: "120",
    iso: 200,
    process: "C-41",
    coverImageUrl: cover("kodak-gold-200-120.jpg"),
    features: ["中画幅大底片", "暖调经典，细节丰富", "宽容度高"],
    scenarios: ["中画幅扫街", "风光", "胶片入门升级"],
    sampleImages: [demoImage(1), demoImage(2)],
    basePriceInCents: 7480,
    deal: { threshold: 15, groupBuyPriceInCents: 6290 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-portra-400-120"),
    name: "Kodak Portra 400",
    brand: "Kodak",
    format: "120",
    iso: 400,
    process: "C-41",
    coverImageUrl: cover("kodak-portra-400-120.jpg"),
    features: ["6×6/6×7 细腻画质", "肤色自然", "弱光稳定"],
    scenarios: ["中画幅人像", "婚礼跟拍", "棚拍"],
    sampleImages: [demoImage(2), demoImage(3)],
    basePriceInCents: 11580,
    deal: { threshold: 15, groupBuyPriceInCents: 9890 },
  }),
  Film.create({
    id: makeFilmId("film-fujifilm-pro400h-120"),
    name: "Fujifilm PRO 400H",
    brand: "Fujifilm",
    format: "120",
    iso: 400,
    process: "C-41",
    coverImageUrl: cover("fujifilm-pro400h-120.svg"),
    description: "已于 2021 年停产，目前市场流通的是库存尾货，售完即止；想长期拍可考虑 Portra 400。",
    features: ["日系清新色调", "高光过渡柔和", "绿色表现通透"],
    scenarios: ["日系人像", "旅行", "生活记录"],
    sampleImages: [demoImage(2), demoImage(1)],
    basePriceInCents: 10880,
    deal: { threshold: 15, groupBuyPriceInCents: 9280 },
  }),
  Film.create({
    id: makeFilmId("film-ilford-hp5-120"),
    name: "Ilford HP5 Plus",
    brand: "Ilford",
    format: "120",
    iso: 400,
    process: "黑白 (D-76)",
    coverImageUrl: cover("ilford-hp5-120.jpg"),
    features: ["中画幅灰阶细腻", "高宽容度", "迫冲潜力大"],
    scenarios: ["中画幅纪实", "街头", "阴天弱光"],
    sampleImages: [demoImage(3), demoImage(2)],
    basePriceInCents: 6480,
    deal: { threshold: 15, groupBuyPriceInCents: 5490 },
  }),

  // ===== 135 补充：柯达主力线 + 富士国行 + 国货 + 创意卷 =====
  Film.create({
    id: makeFilmId("film-kodak-ultramax-400-135"),
    name: "Kodak UltraMax 400",
    brand: "Kodak",
    format: "135",
    iso: 400,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "柯达「全能 400」，室内外通吃的性价比主力卷，颜色偏冷、绿植表现讨喜。",
    features: ["400 度高感通吃", "宽容度高", "价格亲民", "新手第一卷首选"],
    scenarios: ["日常记录", "旅行", "阴天与室内"],
    sampleImages: [demoImage(1), demoImage(3)],
    basePriceInCents: 5500,
    deal: { threshold: 24, groupBuyPriceInCents: 4250 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-portra-160-135"),
    name: "Kodak Portra 160",
    brand: "Kodak",
    format: "135",
    iso: 160,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "Portra 系列最低感光的一支，颗粒最细，适合晴天与棚拍人像。",
    features: ["颗粒极细", "肤色奶油感", "扫描友好"],
    scenarios: ["晴天户外人像", "棚拍", "静物"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 9800,
    deal: { threshold: 15, groupBuyPriceInCents: 7900 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-portra-800-135"),
    name: "Kodak Portra 800",
    brand: "Kodak",
    format: "135",
    iso: 800,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "夜拍与舞台光的救星，高感下依然保持柔和肤色。",
    features: ["高感光夜拍", "肤色依然柔和", "迫冲到 1600 可用"],
    scenarios: ["夜景", "婚礼跟拍", "室内弱光"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 14500,
    deal: { threshold: 12, groupBuyPriceInCents: 11800 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-tmax-100-135"),
    name: "Kodak T-MAX 100",
    brand: "Kodak",
    format: "135",
    iso: 100,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "现代黑白标杆：锐度极高、灰阶层次丰富，适合放大输出。",
    features: ["锐度极高", "灰阶层次丰富", "适合放大"],
    scenarios: ["风光", "建筑", "黑白人像"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 8800,
    deal: { threshold: 15, groupBuyPriceInCents: 6900 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-trix-400-135"),
    name: "Kodak Tri-X 400",
    brand: "Kodak",
    format: "135",
    iso: 400,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "七十多年历史的传奇黑白卷，粗颗粒与高反差是它的招牌味道。",
    features: ["经典粗颗粒", "反差强烈", "纪实味道浓"],
    scenarios: ["街头纪实", "新闻摄影", "弱光黑白"],
    sampleImages: [demoImage(2), demoImage(3)],
    basePriceInCents: 9200,
    deal: { threshold: 15, groupBuyPriceInCents: 7200 },
  }),
  Film.create({
    id: makeFilmId("film-fujifilm-c400-135"),
    name: "Fujifilm C400",
    brand: "Fujifilm",
    format: "135",
    iso: 400,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "富士国行复产的高感负片（原 X-TRA 400 配方路线），性能均衡，拼团性价比高。",
    features: ["色彩清爽", "高感表现稳", "国行新鲜批次"],
    scenarios: ["日常记录", "旅行", "弱光环境"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 5500,
    deal: { threshold: 24, groupBuyPriceInCents: 4250 },
  }),
  Film.create({
    id: makeFilmId("film-ilford-fp4-125-135"),
    name: "Ilford FP4 Plus 125",
    brand: "Ilford",
    format: "135",
    iso: 125,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "依尔福中速黑白，细腻且宽容，是暗房入门最友好的卷之一。",
    features: ["颗粒细腻", "宽容度高", "暗房放大友好"],
    scenarios: ["风光", "静物", "暗房练习"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 6200,
    deal: { threshold: 18, groupBuyPriceInCents: 4800 },
  }),
  Film.create({
    id: makeFilmId("film-lucky-c200-135"),
    name: "乐凯 Lucky C200",
    brand: "乐凯 Lucky",
    format: "135",
    iso: 200,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "国货之光，2026 年复产的 135 彩色负片，价格门槛最低，适合练手试机。",
    features: ["国货新复产", "价格门槛低", "练手不心疼"],
    scenarios: ["新手试机", "日常练习", "大量拍摄"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 3800,
    deal: { threshold: 30, groupBuyPriceInCents: 2900 },
  }),
  Film.create({
    id: makeFilmId("film-shanghai-gp3-100-135"),
    name: "上海 GP3 100",
    brand: "上海 ShangHai",
    format: "135",
    iso: 100,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "老牌国货黑白卷，市面最便宜的选择之一，适合试机和黑白入门。",
    features: ["价格极低", "国货情怀", "试机首选"],
    scenarios: ["试机", "黑白入门", "大量练习"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 2800,
    deal: { threshold: 40, groupBuyPriceInCents: 2200 },
  }),
  Film.create({
    id: makeFilmId("film-cinestill-800t-135"),
    name: "CineStill 800T",
    brand: "CineStill",
    format: "135",
    iso: 800,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "电影卷改制的钨丝灯平衡负片，招牌的红色光晕让它成为夜景氛围神器。",
    features: ["标志性红色光晕", "夜拍氛围感强", "电影感色调"],
    scenarios: ["夜景霓虹", "城市夜拍", "人像氛围"],
    sampleImages: [demoImage(1), demoImage(2)],
    basePriceInCents: 12800,
    deal: { threshold: 12, groupBuyPriceInCents: 9900 },
  }),

  // ===== 120 补充：专业线 + 国货 + 创意卷 =====
  Film.create({
    id: makeFilmId("film-kodak-portra-160-120"),
    name: "Kodak Portra 160",
    brand: "Kodak",
    format: "120",
    iso: 160,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "中画幅最常用的日常专业卷，颗粒细腻、肤色讨喜，晴天户外首选。",
    features: ["中画幅细腻画质", "肤色自然", "扫描友好"],
    scenarios: ["户外人像", "婚礼", "旅行记录"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 12800,
    deal: { threshold: 12, groupBuyPriceInCents: 9900 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-ektar-100-120"),
    name: "Kodak Ektar 100",
    brand: "Kodak",
    format: "120",
    iso: 100,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "色彩饱和浓郁、颗粒极细，中画幅风光的常青选择。",
    features: ["色彩浓郁", "颗粒极细", "锐度高"],
    scenarios: ["中画幅风光", "建筑", "晴天户外"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 11500,
    deal: { threshold: 12, groupBuyPriceInCents: 8800 },
  }),
  Film.create({
    id: makeFilmId("film-kodak-tmax-100-120"),
    name: "Kodak T-MAX 100",
    brand: "Kodak",
    format: "120",
    iso: 100,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "中画幅黑白的高锐度代表，层次丰富，适合大尺寸放大。",
    features: ["锐度极高", "灰阶层次丰富", "适合放大输出"],
    scenarios: ["中画幅风光", "黑白人像", "建筑"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 11800,
    deal: { threshold: 12, groupBuyPriceInCents: 9200 },
  }),
  Film.create({
    id: makeFilmId("film-ilford-fp4-125-120"),
    name: "Ilford FP4 Plus 125",
    brand: "Ilford",
    format: "120",
    iso: 125,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "中画幅中速黑白，细腻稳定，暗房放大表现优秀。",
    features: ["颗粒细腻", "宽容度高", "暗房友好"],
    scenarios: ["中画幅风光", "静物", "暗房练习"],
    sampleImages: [demoImage(1)],
    basePriceInCents: 7800,
    deal: { threshold: 15, groupBuyPriceInCents: 6000 },
  }),
  Film.create({
    id: makeFilmId("film-shanghai-gp3-100-120"),
    name: "上海 GP3 100",
    brand: "上海 ShangHai",
    format: "120",
    iso: 100,
    process: "黑白 (D-76)",
    coverImageUrl: cover("placeholder.svg"),
    description: "目前最便宜的 120 黑白卷之一，用来给新到手的中画幅相机试机最划算。",
    features: ["价格极低", "国货情怀", "试机不心疼"],
    scenarios: ["中画幅试机", "黑白入门", "大量练习"],
    sampleImages: [demoImage(3)],
    basePriceInCents: 3400,
    deal: { threshold: 30, groupBuyPriceInCents: 2600 },
  }),
  Film.create({
    id: makeFilmId("film-lomography-color100-120"),
    name: "Lomography Color Negative 100",
    brand: "Lomography",
    format: "120",
    iso: 100,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "Lomography 中画幅入门负片，色彩偏暖，价格友好，适合日常随拍。",
    features: ["暖调色彩", "价格友好", "日常随拍"],
    scenarios: ["日常记录", "旅行", "朋友聚会"],
    sampleImages: [demoImage(2)],
    basePriceInCents: 6800,
    deal: { threshold: 15, groupBuyPriceInCents: 5200 },
  }),
  Film.create({
    id: makeFilmId("film-cinestill-800t-120"),
    name: "CineStill 800T",
    brand: "CineStill",
    format: "120",
    iso: 800,
    process: "C-41",
    coverImageUrl: cover("placeholder.svg"),
    description: "电影卷改制的中画幅夜拍卷，红色光晕 + 大底片 = 氛围感拉满。",
    features: ["标志性红色光晕", "中画幅夜拍", "电影感色调"],
    scenarios: ["城市夜景", "人像氛围", "霓虹街拍"],
    sampleImages: [demoImage(1), demoImage(3)],
    basePriceInCents: 15800,
    deal: { threshold: 10, groupBuyPriceInCents: 12200 },
  }),
]

const persistence = <A, E>(self: Effect.Effect<A, E>): Effect.Effect<A, PersistenceError> =>
  self.pipe(
    Effect.mapError((e) =>
      new PersistenceError({ message: e instanceof Error ? e.message : String(e) }),
    ),
  )

export const HubRepositoryInMemory = Layer.effect(
  HubRepository,
  Effect.gen(function* () {
    const store = yield* Ref.make(new Map<string, Hub>(seedHubs(new Date()).map((h) => [h.id, h])))
    return HubRepository.make({
      findAll: () => persistence(Ref.get(store).pipe(Effect.map((m) => [...m.values()]))),
      findById: (id: HubId) =>
        persistence(Ref.get(store).pipe(Effect.map((m) => Option.fromNullable(m.get(id))))),
      save: (hub: Hub) => persistence(Ref.update(store, (m) => m.set(hub.id, hub))),
    })
  }),
)

export const FilmRepositoryInMemory = Layer.effect(
  FilmRepository,
  Effect.gen(function* () {
    const store = yield* Ref.make(new Map<string, Film>(seedFilms().map((f) => [f.id, f])))
    return FilmRepository.make({
      findAll: () => persistence(Ref.get(store).pipe(Effect.map((m) => [...m.values()]))),
      findById: (id: FilmId) =>
        persistence(Ref.get(store).pipe(Effect.map((m) => Option.fromNullable(m.get(id))))),
      save: (film: Film) => persistence(Ref.update(store, (m) => m.set(film.id, film))),
    })
  }),
)

export const GroupBuyRepositoryInMemory = Layer.effect(
  GroupBuyRepository,
  Effect.gen(function* () {
    const store = yield* Ref.make(new Map<string, GroupBuy>())
    const keyOf = (hubId: HubId, filmId: FilmId): string => `${hubId}::${filmId}`
    return GroupBuyRepository.make({
      findByHubAndFilm: (hubId: HubId, filmId: FilmId) =>
        persistence(
          Ref.get(store).pipe(Effect.map((m) => Option.fromNullable(m.get(keyOf(hubId, filmId))))),
        ),
      save: (group: GroupBuy) =>
        persistence(Ref.update(store, (m) => m.set(keyOf(group.hubId, group.filmId), group))),
    })
  }),
)
